# picom — style DTOS (léger, X11)
backend = "glx";
vsync = true;

# Ombres
shadow = true;
shadow-radius = 12;
shadow-opacity = 0.6;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-exclude = [
  "class_g = 'firefox' && argb",
  "_GTK_FRAME_EXTENTS@:c"
];

# Fading
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;

# Transparence
inactive-opacity = 0.95;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;
opacity-rule = [
  "100:class_g = 'brave-browser'",
  "100:class_g = 'Brave-browser'",
  "100:class_g = 'Wfica'",
  "100:fullscreen"
];

# Coins arrondis (DTOS-like)
corner-radius = 8;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "class_g = 'dmenu'"
];

# Blur léger
blur-method = "dual_kawase";
blur-strength = 3;
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
